# Generated by Django 5.2.7 on 2025-11-03 03:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(help_text='Nome completo do professor', max_length=200, verbose_name='Nome Completo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do aluno', max_length=200, verbose_name='Nome Completo')),
                ('ra', models.CharField(help_text='Registro Acadêmico único do aluno', max_length=50, unique=True, verbose_name='RA (Registro Acadêmico)')),
                ('password', models.CharField(help_text='Senha com hash', max_length=128, verbose_name='Senha')),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o aluno está ativo no sistema', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['ra'], name='core_aluno_ra_fc99f3_idx'), models.Index(fields=['is_active'], name='core_aluno_is_acti_a8be64_idx')],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da atividade', max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(help_text='Descrição completa da atividade', verbose_name='Descrição')),
                ('prazo_entrega', models.DateField(help_text='Data limite para entrega', verbose_name='Prazo de Entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('professor', models.ForeignKey(help_text='Professor que criou a atividade', on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField(help_text='Resposta do aluno para a atividade', verbose_name='Resposta')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, help_text='Nota atribuída pelo professor', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota (0-10)')),
                ('observacao', models.TextField(blank=True, help_text='Feedback do professor para o aluno', null=True, verbose_name='Observação do Professor')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('corrigido_em', models.DateTimeField(blank=True, null=True, verbose_name='Corrigido em')),
                ('aluno', models.ForeignKey(help_text='Aluno que enviou a resposta', on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to='core.aluno', verbose_name='Aluno')),
                ('atividade', models.ForeignKey(help_text='Atividade que está sendo respondida', on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to='core.atividade', verbose_name='Atividade')),
            ],
            options={
                'verbose_name': 'Submissão',
                'verbose_name_plural': 'Submissões',
                'ordering': ['aluno__nome'],
            },
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['professor', '-created_at'], name='core_ativid_profess_11cd26_idx'),
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['prazo_entrega'], name='core_ativid_prazo_e_cb9b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='submissao',
            index=models.Index(fields=['atividade', 'aluno'], name='core_submis_ativida_5b633b_idx'),
        ),
        migrations.AddIndex(
            model_name='submissao',
            index=models.Index(fields=['nota'], name='core_submis_nota_9f9fd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submissao',
            unique_together={('atividade', 'aluno')},
        ),
    ]
